### ISSUE TITLE
Anime Maids in Sombra Theme

### ISSUE THREAD

**Issue by that-random-humanoid** [VorgunTheBeta/DiscordOverwatchThemes#1]
Whenever you left click on someone's profile and get a pop-up window of their info, the background image it of two anime maids. The "issue" is minor and can be fixed easily by deleting a few lines of text, but I just wanted to let people know :)

**Comment by VorgunTheBeta** [comment]
Yeah sorry, ive fixed it locally but forgot to update it here.
